services:
  - type: web
    name: enviro-backend
    runtime: python
    buildCommand: ""
    startCommand: uvicorn main:app --host=0.0.0.0 --port=$PORT
    envVars:
      - key: SERIAL_PORT
        value: /dev/null  # Fake path (no serial needed on host)
      - key: BAUD_RATE
        value: "9600"
    plan: free
