services:
    - type: web
      name: enviromon
      env: python
      plan: free
      buildCommand: pip install -r requirements.txt
      startCommand: gunicorn -c gunicorn.conf.py main:app
      envVars:
        - key: DATABASE_URL
          value: sqlite:////app/data/sensor_data.db
        - key: SERIAL_BRIDGE_URL
          value: https://243c-2a02-6b67-e460-c500-3973-fdc1-c5df-8fc1.ngrok-free.app/serial
        - key: USE_SERIAL_BRIDGE
          value: true
        - key: AZURE_IOT_HUB_CONNECTION_STRING
          value: Endpoint=sb://iothub-ns-enviromon-65197121-d5a242f1bd.servicebus.windows.net/;SharedAccessKeyName=iothubowner;SharedAccessKey=v/58WaKpYYGNzqOKLrCjCSUW41GVdt9qZAIoTJRodkA=;EntityPath=enviromon
      disks:
        - name: data
          mountPath: /app/data
  ```