services:
  - type: web
    name: enviromon
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app:app
    envVars:
      - key: DATABASE_URL
        value: sqlite:////app/data/sensor_data.db
      - key: SERIAL_BRIDGE_URL
        value: http://localhost:8001/serial
      - key: USE_SERIAL_BRIDGE
        value: true
      - key: AZURE_IOT_HUB_CONNECTION_STRING
        value: HostName=EnviroMonHub2025.azure-devices.net;DeviceId=CloudEnviroMon;SharedAccessKey=your_key_here